---
# tasks file for infra_server_dhcp_dhcpd

# install dhcp server
- name: install dhcp server
  ansible.builtin.dnf:
    name: "{{ dhcpd_package }}"
    state: present

# configure dhcpd.service
- name: configure dhcpd.service
  ansible.builtin.template:
    src: dhcpd.service.j2
    dest: /etc/systemd/system/dhcpd.service

# configure dhcpd.conf
- name: configure dhcpd.conf
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf

# Reload the systemd manager configuration: 
- name: reload the systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: yes

# enable and start dhcpd.service
- name: enable and start dhcpd.service
  ansible.builtin.service:
    name: dhcpd.service
    state: started
    enabled: yes
