---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: dhcpd_server
    image: centos:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
    # published_ports:
    #   - "6767:67/udp"
    #network_mode: host
  - name: dhcpd_client
    image: centos:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
    #network_mode: host
provisioner:
  name: ansible
verifier:
  name: ansible
