---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: dhcpd_client
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  
  - name: dhcp lease test
    command: dhclient -4 tap0 
